project_id = "pxzvpnshhulrsjbeqqhn"

[functions.fetch-whatsapp-contacts]
verify_jwt = true

[functions.fetch-whatsapp-groups]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.support-chat]
verify_jwt = true

[functions.send-messages]
verify_jwt = true

[functions.generate-variations]
verify_jwt = true

[functions.update-message-status]
verify_jwt = false

[functions.update-campaign-status]
verify_jwt = false

[functions.process-scheduled-campaigns]
verify_jwt = false
